### ISSUE TITLE
Customizable "Project" text in top left of appbar

### ISSUE THREAD

**Issue by ethanmay** [equinusocio/material-theme-appbar#31] opened 2016-05-15 20:10 UTC
This would be a very useful feature, as I often have multiple windows open with different project. If the word "Project" defaulted to the name of the folder I have open in Sublime Text, I'd be able to more easily discern between multiple open projects. Love your packages, thank you for your work!

**Comment by equinusocio** [comment] 2016-05-16 07:53
Duplicate of #5 #21

**Closed by equinusocio** 2016-05-16 07:53 UTC
